// API
export const API_TELECOM_COMPANIES = 'telecom-companies';
export const API_TELECOM_TARIFFS = 'telecom-tariffs';
export const API_BANKS = 'banks';
export const API_BANKING_TARIFFS = 'banking-tariffs';

// Actions
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_TELECOM_COMPANIES_SUCCESS = 'GET_TELECOM_COMPANIES_SUCCESS';
export const GET_TELECOM_COMPANIES_FAIL = 'GET_TELECOM_COMPANIES_FAIL';
export const GET_TELECOM_TARIFFS_SUCCESS = 'GET_TELECOM_TARIFFS_SUCCESS';
export const GET_TELECOM_TARIFFS_FAIL = 'GET_TELECOM_TARIFFS_FAIL';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAIL = 'GET_BANKS_FAIL';
export const GET_BANKING_TARIFFS_SUCCESS = 'GET_BANKING_TARIFFS_SUCCESS';
export const GET_BANKING_TARIFFS_FAIL = 'GET_BANKING_TARIFFS_FAIL';
